Loono-cz/loono

lib/l10n/intl_cs.arb
lib/ui/screens/create_account.dart
lib/ui/screens/onboarding/allow_notifications.dart
lib/ui/screens/onboarding/gender.dart
lib/ui/widgets/skip_button.dart

https://cesko-digital.atlassian.net/browse/LOON-179
vše sedí, jen:
- změněn text Skip buttonu defaultně na z "Přeskočit" na "Přeskočit dotazník" (tohle je tam vickrat)
- odebrán padding zeshora u SkipButtonu
- update routes
- přidány TODO na lokalni uložiště

LOON-179 Screen update

---

assets/icons/check.svg
lib/constants.dart
lib/ui/widgets/progress_dots.dart

https://cesko-digital.atlassian.net/browse/LOON-193
updatnutí těch indikatorů u doktorů
- před
- po

LOON-193 Doctor progress indicators - update

---

ios/Podfile.lock
lib/ui/screens/about_health/about_health.dart
lib/ui/screens/main/main_screen.dart
lib/utils/registry.dart
pubspec.lock
pubspec.yaml

Added basic version of webview for explore section to allow further website testing and debugging.
I choose https://inappwebview.dev/docs/ for its great documentation and build-in capabilities. It is possible to add advanced 
functionalities later on, such as JS and CSS injections or website preload, caching etc.

Explore section webview

---

lib/ui/widgets/fallback_account_content.dart

https://cesko-digital.atlassian.net/browse/LOON-372

fix: placeholder text style

---

lib/models/healthcare_provider.dart
lib/repositories/healthcare_repository.dart
lib/services/map_state_sevice.dart
lib/ui/widgets/find_doctor/search_text_field.dart
pubspec.lock
pubspec.yaml
test/services/map_state_sevice.dart

- handlování případu, kdy se nezobrazovaly výsledky s diakritikou; viz https://cesko-digital.slack.com/archives/C026X0CMF40/p1639867300170900

fix: improve healthcare providers query search

---

lib/ui/widgets/prevention/examination_card.dart

Wrapped SvgPicture in ClipRRect

corner_rounded

---

lib/ui/screens/onboarding/carousel/carousel_second.dart
lib/ui/screens/onboarding/carousel/carousel_third.dart
lib/ui/widgets/onboarding/carousel/button.dart

Added new parameter for height multiplier

bottom_position

---

lib/utils/image_utils.dart

default_front_camera

---

lib/ui/widgets/settings/app_bar.dart

Changed app bar icons accordingly to design

app_bar_icons

---

lib/ui/widgets/onboarding/carousel/story_page.dart
lib/ui/widgets/video_player.dart

Autoplay intro video set to mute

default_mute

---

lib/ui/screens/settings/update_profile.dart

způsobeno mnou v #96 :D
fix `LateInitializationError` - do metody byla passnuta hodnota null a ve switchu nebyla ohandlována

fix: update settings screen crash

---

lib/models/user.dart
lib/repositories/user_repository.dart
lib/router/app_router.gr.dart
lib/services/db/database.g.dart
lib/ui/screens/prevention/calendar/calendar_list.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/screens/settings/update_profile.dart

po diskuzi s Janou chybělo u kalendáře jen jediné - pokud už si člověk dříve event přidal, tento kalendář se nasatví jako defaultní a při příštím kliknutí na 'Přidat do kalendáře' se už opět nemusí vybírat z kalendářů, ale vybere se ten stejný jako minulý

feat(LOON-361): finish calendar integration

---

lib/router/app_router.gr.dart
lib/ui/screens/main/pre_auth/continue_onboarding_form.dart

- fix build
- fix login routy - vyřešeno pushnutím deklarativní routy, a pak hned nedeklarativníma .. a vypadá, že to funguje.

fix: build & onboarding login route (LOON-518)

---

lib/helpers/type_converters.dart
lib/models/user.dart
lib/repositories/user_repository.dart
lib/services/api_service.dart
lib/services/auth/auth_service.dart
lib/services/db/database.dart
lib/services/db/database.g.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/widgets/badges/badge_composer.dart

https://cesko-digital.atlassian.net/browse/LOON-402
Napojení badges na api. Už se zobrazují na postavičce.
Rozšířil jsem User model v DB o badges. To prosím double checknout, jestli jsem něco nerozvrtal :)

LOON-402: Display avatar badges

---

lib/repositories/user_repository.dart
lib/ui/screens/main/main_screen.dart
lib/ui/screens/prevention/questionnaire/schedule_examination.dart
lib/ui/screens/settings/leaderboard.dart
lib/ui/screens/settings/open_settings.dart
lib/ui/widgets/prevention/examination_confirm_sheet.dart

Exposnul jsem sync metodu v user repository, aby šlo aktualizovat profil po získání bodů a badges. Jana zjistila při testování, že se jí hrdina nemění.
A přidal jsem 2 spodní paddingy do setting, kvůli ios

fix(Badges): Update profile after achievement

---

ios/Podfile.lock
lib/ui/screens/prevention/prevention.dart
lib/ui/widgets/prevention/profile_button.dart
lib/ui/widgets/settings/avatar.dart
lib/ui/widgets/settings/leaderboard_tile.dart

Settings button změněno na obrázrek profilu. Considered final by Otakar.

feat(UI): profile button

---

lib/helpers/social_login_helpers.dart
lib/l10n/intl_cs.arb
lib/models/social_login_account.dart
lib/router/app_router.gr.dart
lib/services/auth/auth_service.dart
lib/services/auth/failures.dart
lib/services/auth/failures.freezed.dart
lib/ui/screens/logout.dart
lib/ui/screens/main/pre_auth/login.dart
lib/ui/screens/main/pre_auth/onboarding_form_done.dart
lib/ui/screens/onboarding/fallback_account/email.dart
lib/ui/screens/onboarding/fallback_account/nickname.dart
lib/ui/screens/onboarding/gamification_introduction.dart
lib/ui/screens/settings/after_deletion.dart
lib/ui/widgets/social_login_button.dart
pubspec.lock

Vytvářet účet se nemá hned po přihlášení tím social loginem na Main screeně, ale až kliknutím na Vytvořit účet na email screeně. Tohle by mělo taky zaručovat že bude mít zadaný vždycky email i nickname, pokud by se náhodou nezískal ze social loginu. Má se dát i v tomto vracet zpět, ale UI věci přidám v dalším PR. IMO tohle řešení asi není úplně moc clean.. ideas welcomed
https://cesko-digital.atlassian.net/browse/LOON-409 - pokud vyplní dotazník a přihlásí se a má již existující účet, má ho to pustit ale má vyskočit hláška (jaká, stále nevím:D)
https://cesko-digital.atlassian.net/browse/LOON-506

feat(onboarding): register user upon clicking registration button

---

lib/ui/screens/prevention/self_examination/self_faq_content.dart
lib/utils/registry.dart

přidán blacklist cest které nemají dělat retry na základě #138. @mzdm tahle cesta stačí nebo potřebujeme ještě nějaké přidat?

fix(networking): Retry blacklist

---

lib/helpers/type_converters.dart
lib/repositories/healthcare_repository.dart
lib/services/map_state_sevice.dart
lib/ui/screens/find_doctor/find_doctor.dart

- chyba při deserializaci -> data doktorů se nenačetly
- update indikátoru podle designu

fix(maps): json decoding error & update progress indicator

---

lib/constants.dart
lib/ui/widgets/fallback_account_content.dart

JIRA: https://cesko-digital.atlassian.net/browse/LOON-373

LOON-373: add error color for inputs

---

lib/helpers/examination_extensions.dart
lib/services/auth/auth_service.dart
lib/utils/crypto_utils.dart

- report od Jany že registrace Applem nefunguje, nevím úplně kde je chyba, tak fix trochu naslepo.. 😃

fix(onboarding): apple login not working

---

lib/helpers/onboarding_state_helpers.dart
lib/router/app_router.dart
lib/router/app_router.gr.dart
lib/router/sub_routers/onboarding_wrapper_screen.dart
lib/ui/screens/onboarding/allow_notifications.dart
lib/ui/screens/onboarding/doctors/dentist.dart
lib/ui/screens/onboarding/doctors/dentist_date.dart

https://cesko-digital.atlassian.net/browse/LOON-408
- podle [flow diagramu](https://i.imgur.com/1FPfmsu.jpg) se má na ios zobrazit notifikační screena po zubaři, pokud se předtím u žádný prohlídky nespecifikovalo datum

fix(LOON-408): display notification screen after dentist

---

lib/services/auth/auth_service.dart

- nešlo se zaregistrovat - podle všeho za to (asi) může zapnutá anonymizace (takže se nezískal email) -> vyhodil se unknown error

fix(auth): apple login again

---

.github/workflows/continuous-integration.yml
.github/workflows/tests.yml

- cache flutter sdk (time save ~40s, ale jak kdy)
- přehozeny flutter verze nahoru do envu, hardcodované v těch filech se už celkem ztrácely

feat(ci): cache flutter sdk

---

lib/helpers/map_variables.dart
lib/loono.dart
lib/ui/screens/about_health/about_health.dart

https://cesko-digital.atlassian.net/browse/LOON-483
Využívá stejnou logiku pro hybridní kompozici jako webview. Pouze pro androids >= 10. 
Zdá se že funguje. Mapa okamžitě po otevření fadene namísto bílé obrazovky

feat(LOON-483): Map hybrid composition

---

lib/helpers/type_converters.dart
lib/models/search_result.dart
lib/models/user.dart
lib/router/app_router.dart
lib/router/app_router.gr.dart
lib/services/db/database.g.dart
lib/services/map_state_sevice.dart
lib/ui/screens/find_doctor/doctor_search_detail.dart
lib/ui/widgets/find_doctor/search_text_field.dart

https://cesko-digital.atlassian.net/browse/LOON-490

feat(LOON-490): doctor search, part 1

---

lib/repositories/user_repository.dart
lib/services/notification_service.dart
lib/ui/screens/settings/after_deletion.dart
lib/utils/app_clear.dart
lib/utils/registry.dart

https://cesko-digital.atlassian.net/browse/LOON-552
~~cekam na Radka na confirm jestli se setnulo~~ confirmnute

feat(LOON-552): set user id for OneSignal notifications

---

lib/ui/screens/prevention/prevention.dart
lib/ui/widgets/avatar_arrow_bubble.dart

výšku už nevypočítávám ale beru z layout builderu. Poupravil jsem pořadí ve stacku prevence. Mezeru jsem testoval na iphonu 8 a mělo by to pomoct

fix(UI): just another arrow fix

---

lib/l10n/intl_cs.arb
lib/repositories/calendar_repository.dart
lib/router/guards/check_is_logged_in.dart
lib/ui/screens/find_doctor/doctor_search_detail.dart
lib/ui/screens/onboarding/gamification_introduction.dart
lib/ui/screens/prevention/examination_detail/examination_badges.dart
lib/ui/screens/prevention/prevention.dart
lib/ui/screens/settings/leaderboard.dart
lib/ui/screens/settings/open_settings.dart
lib/ui/widgets/badges/badge_composer.dart
lib/ui/widgets/custom_navigation_bar.dart
lib/ui/widgets/no_connection_message.dart
lib/ui/widgets/prevention/examinations_sheet_overlay.dart
lib/ui/widgets/settings/leaderboard_tile.dart
pubspec.lock

- default reminders for calendar event [LOON-415](https://cesko-digital.atlassian.net/browse/LOON-415)
-  some small ui fixes

feat(LOON-415): set reminders for calendar event + ui fixes

---

integration_test/test_helpers/dart_objects_gens.dart
integration_test/test_sets/app/test_data/default_test_data.dart
integration_test/test_sets/settings/test_cases/update_profile/loon_554_update_profile_positive_scenario.dart
integration_test/test_sets/settings/test_cases/update_profile/loon_555_update_profile_negative_scenario.dart
lib/repositories/user_repository.dart
lib/services/api_service.dart
lib/ui/screens/force_update.dart
pubspec.lock
pubspec.yaml

- Updatovaná verze api kvůli typo v preferredEmail
- fix force update pozice CTA

fix(API): Api update

---

assets/icons/card_circle.svg
assets/icons/hero_background.svg
lib/ui/screens/onboarding/gamification_introduction.dart
lib/ui/screens/prevention/prevention.dart
lib/ui/widgets/prevention/examination_card.dart
lib/ui/widgets/prevention/self_examination/self_examination_card.dart

Nastyloval jsem karty vyšetření a přidal pozadí hrdiny do prevence a onboardingu. Nenašel jsem k tomu žádný task.

feat(UI): Examination cards background

---

lib/helpers/examination_extensions.dart
lib/l10n/intl_cs.arb
lib/repositories/user_repository.dart
lib/ui/screens/find_doctor/doctor_search_detail.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/screens/prevention/self_examination/detail_screen.dart
lib/ui/screens/prevention/self_examination/educational_screen.dart
lib/ui/screens/prevention/self_examination/has_finding_screen.dart
lib/ui/screens/settings/edit_photo.dart
lib/ui/widgets/find_doctor/search_detail_search_history_list.dart
lib/ui/widgets/find_doctor/search_result_list_item.dart
lib/ui/widgets/find_doctor/search_results_list.dart
lib/ui/widgets/prevention/examination_card.dart
lib/ui/widgets/prevention/examinations_sheet_overlay.dart
lib/ui/widgets/prevention/self_examination/how_it_went_sheet.dart
lib/ui/widgets/prevention/self_examination/self_examination_card.dart

- fix nějakých drobných issues v hledání doktora + pozn. od Otakara (zvýšení search historie)
- stylingy u prevence a samovyšetření
- cachovani pozicovani karet na main screeně at se nerebuildují když nejdou vidět - způsobovalo blikání/posunování když se rychle scrollovalo
- fix api callů u samovyšetření - blokovalo mě to v testech :D
BTW. stále se duplikují doktoři v post-auth main screeně při přepínání tabů 🤔 (v pre-auth ne, tam mezi taby se persistuje stav). Moc jsem to nezkoumal, asi tam něco hapruje v tom u toho StreamBuilderu kde se to volá dokola

fix(api): self examination api fixes + text styles

---

lib/helpers/type_converters.dart
lib/models/apple_account_info.dart
lib/models/apple_account_info.freezed.dart
lib/models/apple_account_info.g.dart
lib/models/social_login_account.dart
lib/services/auth/auth_service.dart
lib/services/auth/failures.dart
lib/services/secure_storage_service.dart
lib/utils/app_clear.dart
lib/utils/registry.dart
pubspec.lock
pubspec.yaml

- TLDR: Apple exposne user info (email, name) [jen při první autorizaci](https://developer.apple.com/forums/thread/121496). Email potřebujem k tomu, abychom zjistili jestli účet už nemá vytvořenej. Toto PR cachuje tato data při první autorizaci do secure storage (v případě iOS Keychain)
- bude šilene debugovat pokud nebude fungovat na poprvé :D testovat to bude asi zase Petr V ..

feat(auth): store securely apple account info on the first authorization

---

lib/helpers/date_helpers.dart
lib/helpers/date_without_day.dart
lib/helpers/examination_detail_helpers.dart
lib/ui/screens/onboarding/fallback_account/email.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/widgets/prevention/change_last_visit_sheet.dart
lib/ui/widgets/prevention/examination_edit_modal.dart
lib/ui/widgets/prevention/examination_progress_content.dart
lib/ui/widgets/prevention/last_visit_sheet.dart

https://cesko-digital.atlassian.net/browse/LOON-538

edit last visited month

---

lib/l10n/intl_cs.arb
lib/ui/screens/settings/update_profile.dart

https://cesko-digital.atlassian.net/browse/LOON-557

feat(LOON-557): Terms and conditions

---

README.md
integration_test/setup.dart
integration_test/test_sets/app/test_cases/be_flow.dart
integration_test/test_sets/be_test.dart
integration_test/test_sets/onboarding/pages/gamification_introduction_page.dart
integration_test/test_sets/onboarding/pages/onboarding_form_done_page.dart
integration_test/test_sets/onboarding/pages/sign_up_email_page.dart
integration_test/test_sets/onboarding/pages/sign_up_nickname_page.dart
integration_test/test_sets/prevention/pages/prevention_main_page.dart
integration_test/test_sets/prevention/pages/self_examination/detail/no_finding_reward_page.dart
integration_test/test_sets/settings/pages/open_settings_page.dart
integration_test/test_sets/settings/pages/update_profile/update_profile_page.dart
lib/models/examination_questionnaire.dart
lib/router/app_router.gr.dart
lib/services/auth/auth_service.dart
lib/ui/screens/main/pre_auth/onboarding_form_done.dart
lib/ui/screens/onboarding/fallback_account/email.dart
lib/ui/screens/onboarding/fallback_account/nickname.dart
lib/ui/screens/onboarding/gamification_introduction.dart
lib/ui/screens/prevention/self_examination/no_finding_screen.dart
lib/ui/widgets/prevention/profile_button.dart

Narozdíl od integračních frontend (UI) testů (#205), tento test testuje reálné API a Firebase autentifikaci. Funguje to tak, že se přes `Firebase Admin SDK` vygeneruje Custom Token (vydrží cca 1h), který se dá použít jako přihlašovací metoda ve `Firebase Auth` (`signInWithCustomToken`). Tato metoda je povolená jen v debug módu a dev flavor, takže nemůže dojít k tomu že by se to volalo v produkci.
Momentálně se musí ten token vygenerovat ručně z 1 skriptu, ale to bude taky zautomatizované s Firebase Test Lab přes CI/CD.
Testovací flow:
```
1. Proceed through the onboarding form
2. Perform sign up with Firebase and send onboarding data via Onboarding API
3. Verify account is created and receives badge(s) and gets valid list of check-ups
4. Verify the user can successfully perform a …
```

feat(tests): backend integration tests

---

.github/workflows/tests.yml
assets/supported_apis.yaml
lib/services/examinations_service.dart
lib/ui/screens/prevention/questionnaire/schedule_examination.dart
lib/ui/widgets/prevention/change_last_visit_sheet.dart
lib/utils/registry.dart

částečně upravuje chování [LOON-323](https://cesko-digital.atlassian.net/browse/LOON-323). Nějak divně se v té prevenci chová BE. Hlášeno Radkovi

fix(ui): last visit date fix

---

lib/services/map_state_sevice.dart
lib/ui/screens/find_doctor/find_doctor.dart
lib/ui/widgets/find_doctor/bottom_sheet_overlay.dart
lib/utils/map_utils.dart

- po kliknutí na cluster se zobrazí dole jen doktoři v tom clusteru (blokne se filtrování při pohybu na mapě dokud je nějaký doktor v tom regionu, nenapadlo mě jak jinak :D)
- fix duplikování doktorů při switchování mezi taby po loginu
- hide bottom sheetu pokud není žádnej doktor v okolí
- nějaké perf optimizace (select místo watch u provideru)
edit: v posledním commitu ještě drobný fix resetovani selektnutyho clusteru pri clicku na item v bottom sheetu

fix(ui): find doctor fixes

---

lib/helpers/examination_extensions.dart
lib/ui/screens/find_doctor/find_doctor.dart
lib/ui/screens/onboarding/birthdate.dart
lib/utils/app_clear.dart

- fix: ordering v prohlidkach [LOON-593](https://cesko-digital.atlassian.net/browse/LOON-593)
- fix: age validation onboarding [LOON-585](https://cesko-digital.atlassian.net/browse/LOON-585)
- fix exception kdy neměl data ve FB Storage a nesmazaly se tak úplně data z db
- přidán error state k loading indicatoru ve Find Doctor -> pokud je error, dá se dát refresh který stahne/loadne případně data znovu (testovat se da na clean appce s vypnutym internetem a pak se zapne)

fix(ui): prevention & find doctor fixes

---

lib/loono.dart
lib/router/app_router.gr.dart
lib/services/webview_service.dart
lib/ui/screens/about_health/about_health.dart
lib/ui/screens/main/main_screen.dart
lib/ui/screens/main/pre_auth/pre_auth_main_screen.dart
lib/utils/registry.dart

Přece jenom jsem fixnul tu back action v pre-auth webview. Usnadní to později i refactor na AutoTabsScaffold. Byl tam nějaký konflikt multiple scaffolds a WillPopScopes, tak jsem ten controller přesunul do provideru.

fix(webview): Webview controller

---

lib/ui/widgets/prevention/examination_edit_modal.dart

https://cesko-digital.atlassian.net/browse/LOON-581

LOON-581 examination date update fix

---

.github/workflows/backend-tests.yml
lib/l10n/intl_cs.arb
lib/ui/screens/onboarding/birthdate.dart
lib/ui/screens/prevention/self_examination/educational_screen.dart
lib/ui/widgets/find_doctor/search_doctor_card.dart

fix věku (again), má být 18 a starší https://cesko-digital.atlassian.net/browse/LOON-585
https://cesko-digital.atlassian.net/browse/LOON-601
+ splash efekt ještě k těm kartám u doktora

fix(ui): prevention fixes

---

integration_test/test_sets/prevention/test_cases/self_examination/detail/loon_566_self_exam_detail_male.dart
integration_test/test_sets/prevention/test_cases/self_examination/detail/loon_567_self_exam_detail_female.dart
lib/helpers/achievement_helpers.dart
lib/helpers/examination_extensions.dart
lib/l10n/intl_cs.arb
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/screens/prevention/self_examination/detail_screen.dart
lib/ui/widgets/prevention/change_last_visit_sheet.dart

https://cesko-digital.atlassian.net/browse/LOON-596
Odesílání správného statusu prohlídky a pár drobných úprav prevence. Mělo by opravovat i stav [LOON-597](https://cesko-digital.atlassian.net/browse/LOON-597), jen tam nesedí datum včasného objednání. Ještě dořeším s Janou, jaký je požadovaný stav a pošlu v novém PR

feat(LOON-596): Unknown last visit

---

lib/services/map_state_sevice.dart

https://cesko-digital.atlassian.net/browse/LOON-572
pokud existovalo více měst se stejným jménem, zobrazilo se jen 1. Teď se ve výsledcích zobrazí všechna + do závorky přidá PSČ
- je tam edge case, že třeba Praha 1 apod. má dalších x PSČ viz obr. Takže je tam menší "hack" na porovnávání vzdáleností...
aby to vypadalo takto:
P.S: yep ta metoda je trošku šílenější. But if it works, it works :D

 fix(LOON-572): distinguish same cities based on postal code

---

lib/router/app_router.gr.dart
lib/ui/screens/about_health/about_health.dart
lib/ui/screens/main/main_screen.dart
lib/ui/screens/main/pre_auth/pre_auth_main_screen.dart

https://cesko-digital.atlassian.net/browse/LOON-609
Prozatímní funkční řešení. Šlo by asi řešit i jinak a lépe

feat(webview): explore section back button

---

assets/maps/map-style.json
lib/ui/widgets/find_doctor/map_preview.dart
pubspec.yaml

https://cesko-digital.atlassian.net/browse/LOON-638

fix(LOON-638): use custom styled maps

---

lib/l10n/intl_cs.arb
lib/repositories/calendar_repository.dart
lib/ui/screens/prevention/self_examination/has_finding_screen.dart
lib/ui/screens/settings/after_deletion.dart
lib/ui/widgets/find_doctor/map_preview.dart

https://cesko-digital.atlassian.net/browse/LOON-639
https://cesko-digital.atlassian.net/browse/LOON-645
https://cesko-digital.atlassian.net/browse/LOON-641

fix(ui): some ui fixes

---

lib/ui/screens/prevention/prevention_screen.dart
lib/ui/widgets/badges/badge_composer.dart

https://cesko-digital.atlassian.net/browse/LOON-618

feat(LOON-618): show/hide badge overview on click

---

lib/ui/widgets/prevention/datepicker_sheet.dart

https://cesko-digital.atlassian.net/browse/LOON-594
Allowuje se i dnešní den, s tím že se time nastavuje až v dalším sheetu, takže pokud by nastavil datum objednání třeba 2h před aktuálním časem tak to pak případně failne při API requestu

fix(LOON-594): allow ordering for a check-up at the same day

---

lib/router/app_router.gr.dart
lib/ui/screens/about_health/about_health.dart
lib/ui/screens/main/main_screen.dart
lib/ui/screens/main/pre_auth/pre_auth_main_screen.dart
pubspec.lock
pubspec.yaml

https://cesko-digital.atlassian.net/browse/LOON-611
- fixnuto otevírání youtube a spotify. Při zachování embed funkcionality
- po roce velký update webview 🎉
- @mzdm přepsal jsem ti zobrazovní back arrow, protože to bylo na iOS vždy o jeden krok opoždeno

fix(LOON-611): Fix YT and spotify url launch

---

integration_test/test_sets/app/test_cases/be_flow.dart
integration_test/test_sets/be_test.dart
integration_test/test_sets/onboarding/pages/questionnaire/doctor_cca_last_visit_page.dart
integration_test/test_sets/onboarding/pages/questionnaire/doctor_date_picker_page.dart
integration_test/test_sets/prevention/pages/examination/examination_detail_page.dart
integration_test/test_sets/prevention/pages/prevention_main_page.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/widgets/custom_date_picker.dart
lib/ui/widgets/custom_time_picker.dart
lib/ui/widgets/prevention/datepicker_sheet.dart
lib/ui/widgets/prevention/examination_cancel_sheet.dart
lib/ui/widgets/prevention/examination_edit_modal.dart
lib/ui/widgets/prevention/examination_new_sheet.dart
lib/ui/widgets/prevention/examination_progress_content.dart
lib/ui/widgets/prevention/examinations_sheet_overlay.dart

https://cesko-digital.atlassian.net/browse/LOON-591
https://cesko-digital.atlassian.net/browse/LOON-592 (kromě kalendáře)
Rozšířil jsem BE test na Prevenci vícemené scénář viz Jira links
- vyplnění nových dotazníků (očař, kožař), jednou s výsledkem kdy se získá badge a bodym, podruhé ne
- objednání se na prohlídku
- zrušení prohlídky
@MartinMacek pokud budeš chtit testovat, můžu zase poslat vygenerovanej token nebo jestli máš Python tak bych ti poslal 1 file abys ho mohl generovat

feat(tests): extend integration BE test

---

pubspec.lock
pubspec.yaml

obsahuje fix na feedback form (zatím funkční jenn pro přihlášené)

fix(api): update loono_api

---

lib/services/api_service.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/screens/prevention/prevention_screen.dart
lib/ui/screens/prevention/self_examination/detail_screen.dart
lib/ui/widgets/feedback/feedback_form_content_sheet.dart
pubspec.lock
pubspec.yaml

- uprava z API aby mohl posilat i neautentifikovany
- jeste uprava reposition buttonu https://cesko-digital.atlassian.net/browse/LOON-607

fix(ui): adjust to feedback form api changes

---

lib/services/map_state_sevice.dart
lib/ui/screens/about_health/about_health.dart
lib/ui/widgets/find_doctor/map_preview.dart
lib/utils/map_utils.dart

https://cesko-digital.atlassian.net/browse/LOON-654
vypnuto promptování location permissions při prvním otevření mapy. Nyní se promptuje až po stisknutí floating location buttonu. 
V jiném PR ještě dořeším [666](https://cesko-digital.atlassian.net/browse/LOON-666)
Taky po dohodě s Janou jsem přidal feedback button nad webview. Prej není nic víc potřeba

feat(LOON-654): Disable init permission prompt

---

lib/ui/screens/find_doctor/find_doctor.dart
lib/ui/widgets/find_doctor/bottom_sheet_overlay.dart

https://cesko-digital.atlassian.net/browse/LOON-640
Vyřešeno Sliver appbarem. Ještě by šlo udělat listview nezávislé na DraggableScrollableSheet, jen jako child ale pak by se ten sheet nevysunoval během scrollu ale jen za tu "handle". Nezdá se mi že by to bylo dobrý UX, tak nechávám takhle.
Z jiry jsem ještě vyvodil, že ta mapa má fadovat do bílé při vysunutí bottom sheetu.

feat(LOON-640): Doctors bottom sheet handle

---

lib/helpers/examination_detail_helpers.dart
lib/ui/screens/prevention/examination_detail/examination_badges.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/widgets/badges/self_exam_badges_sheet.dart

https://cesko-digital.atlassian.net/browse/LOON-612
a
https://cesko-digital.atlassian.net/browse/LOON-619
https://cesko-digital.atlassian.net/browse/LOON-614

fix(ui): Prevention UI fixes

---

lib/services/examinations_service.dart
lib/ui/screens/main/main_screen.dart
lib/ui/widgets/custom_navigation_bar.dart
lib/ui/widgets/notification_icon.dart

jde o přidání té notifikační ikonky do Bottom Nav Baru (v post-auth), pokud mu zbývá vyplnit nějaký dotazníky, může provést samovyšetření, nebo má zadat zda byl na preventivní prohlídce
issue jsem na to nenašel, logiku chovani jsem si odhadl :D

feat(ui): bottom nav notification icon

---

lib/l10n/intl_cs.arb
lib/router/app_router.dart
lib/router/app_router.gr.dart
lib/ui/screens/find_doctor/find_doctor.dart
lib/ui/widgets/feedback/feedback_form_content_sheet.dart
lib/ui/widgets/find_doctor/bottom_sheet_overlay.dart
lib/ui/widgets/how/loon_botton_sheet.dart
lib/ui/widgets/prevention/datepicker_sheet.dart
lib/ui/widgets/prevention/examination_cancel_sheet.dart
lib/ui/widgets/prevention/examination_new_sheet.dart

fixy viz komenty Jira
- https://cesko-digital.atlassian.net/browse/LOON-485
- https://cesko-digital.atlassian.net/browse/LOON-607
- a clkem funny bug - SliverAppBar u doktora mel backbutton v preauth :D

fix: find doctor back route fix

---

lib/ui/screens/prevention/questionnaire/schedule_examination.dart
lib/ui/screens/prevention/self_examination/result_from_doctor.dart
lib/ui/widgets/async_button.dart
lib/ui/widgets/button.dart
lib/ui/widgets/prevention/self_examination/how_it_went_sheet.dart
lib/ui/widgets/universal_doctor.dart

jen takovej menší UX improvement pro uživatele, když se volá API tak se tam přepne na light buttonu ten loader (tyto buttony jsou např. u samovyšetření)

feat(ux): add more loading buttons

---

lib/ui/screens/prevention/self_examination/detail_screen.dart
lib/ui/screens/prevention/self_examination/educational_screen.dart
lib/ui/screens/prevention/self_examination/self_faq_section.dart
lib/ui/widgets/prevention/harm_disclosure.dart

Protože nám neprošlo iOS review kvůli [Physical Harm](https://developer.apple.com/app-store/review/guidelines/#physical-harm), přidávám do samovyšetření odkazy na zdroje. Nechal jsem hardcoded, protože obsah a místo je z toho docela nejasné, tak tohle je spíš takový první pokus a pravděpodobně budeme ještě měnit.

feat(legal): Apple review disclaimers

---

bin/ci_workflow_scripts/verify_formatting.sh
lib/services/map_state_sevice.dart

viz i jiné PRs https://github.com/Loono-cz/loono/pull/261, asi přestalo fungovat jak se přesunulo do těch shell skriptů

fix(ci): formatting workflow

---

.gitignore
lib/helpers/map_variables.dart
lib/services/map_state_sevice.dart

Nové intro video se na ios zobrazovalo jako černá obrazovka. Asi nějaká chyba v metadatech. Po conversion se zdá že funguje. Nechal jsem 5MB. Míň už docela upadala kvalita.
Taky jsem přidal top padding do visible regionu na [žádost Otakara](https://cesko-digital.atlassian.net/browse/LOON-647?focusedCommentId=17442&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17442)
a přidal jsem do gitignoru fvm. Začal jsem používat, protože jinde pomalu přecházím na flutter 3

fix(UI): Intro video

---

lib/repositories/healthcare_repository.dart
lib/services/map_state_sevice.dart
lib/ui/widgets/feedback/feedback_button.dart
lib/utils/map_utils.dart
lib/utils/registry.dart

- trochu upraveno clusterování (když se zadala Praha 1 bylo tam šíleně moc značek), teď jich je méně aby nesekalo
- custom marker doktora se cachne při spuštění appky a nevykresluje se tak pokaždé z png obrázku při každém pohybu mapy
a https://cesko-digital.atlassian.net/browse/LOON-679

perf(maps): improve map performance

---

ios/Podfile.lock

návrat ke cocoapods 1.11.2 protože je to defaultní verze v codemagicu

fix(pods): Use cocoapods 1.11.2

---

.github/workflows/frontend-tests.yml
README.md
integration_test/test_helpers/widget_tester_extensions.dart
integration_test/test_sets/app/test_cases/be_flow.dart
integration_test/test_sets/settings/pages/update_profile/edit_email_page.dart
integration_test/test_sets/settings/pages/update_profile/edit_nickname_page.dart
integration_test/test_sets/settings/test_cases/update_profile/loon_554_update_profile_positive_scenario.dart

Flakiness se tuším za poslední měsíc neobjevila ... byla tam jedna zapomenutá 1s delay, kdy se to ještě spouštělo na emulátorech. Zkusil bych odstranit, případně můžem dát revert / adjustovat :D  ... 
BE test zkrácen cca z 2 minut na minutu.. frontend testy jsou o cca 4-5min kratší 🚀
Na Firebase Test Lab BE test prošel:
https://user-images.githubusercontent.com/67197047/170515007-e197a072-f157-4766-8ca8-9e5bfd0d5a47.mp4

feat(tests): speed up integration tests execution

---

lib/constants.dart
lib/helpers/examination_extensions.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/widgets/prevention/datepicker_sheet.dart
lib/ui/widgets/prevention/examination_progress_content.dart

Verze 0.2.301
HIGH
v rozkliku detailu prohlídky se nezobrazuje uvedená poznámka
LOW
progres bar obsahuje slovo Preventivni prohlidka
souvisejici prohlidky obcas obsahuji spatna data (zrejme i cancellovane prohlidky)
Fixed.

Done bug fixing.

---

ios/Podfile.lock
lib/router/app_router.gr.dart
lib/services/examinations_service.dart
lib/ui/widgets/prevention/examination_delete_sheet.dart

fix: delete examination; fix: flushbar memory leak

---

lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/widgets/prevention/change_last_visit_sheet.dart

https://github.com/Loono-cz/loono/issues/356#issuecomment-1272583644

fix: last doxtor visit datepicker title and validation

---

lib/ui/screens/main/main_screen.dart
lib/ui/screens/main/pre_auth/pre_auth_main_screen.dart

https://github.com/Loono-cz/loono-tasks/issues/92

fix: no connecttion flushbar fix

---

ios/Podfile.lock
lib/models/apple_account_info.freezed.dart
lib/models/apple_account_info.g.dart
lib/router/app_router.gr.dart
lib/ui/screens/onboarding/fallback_account/submit_account.dart
pubspec.lock
pubspec.yaml

https://github.com/Loono-cz/loono-tasks/issues/128

fix: delete user using BE instead of FB only when acc exists

---

ios/Podfile
ios/Podfile.lock
pubspec.lock

feat: pod min platform iOS 12.0

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
pubspec.lock

android target SDK 31

---

lib/ui/screens/onboarding/carousel/carousel_second.dart
lib/ui/screens/onboarding/fallback_account/newsletter_and_gdpr.dart
lib/ui/widgets/onboarding/carousel/button.dart
lib/ui/widgets/onboarding/carousel/carousel_content.dart

https://github.com/Loono-cz/loono-tasks/issues/141

Fix/nejede onboarding#141

---

.gitignore
perf_tests/LoonoPerfTest-origin.jmx
perf_tests/LoonoPerfTest-v2.jmx
perf_tests/LoonoPerfTest-v3.jmx
perf_tests/read_me.md

Perf testing

---

ios/Runner/Info.plist

Pridal jsem 'NSLocationAlwaysAndWhenInUseUsageDescription' key do 'info.plist' pro iOS
https://github.com/Loono-cz/loono-tasks/issues/153

Problémy s Dev verzí v Appstore #153

---

ios/Podfile.lock
lib/ui/screens/main/main_screen.dart
lib/ui/screens/main/pre_auth/pre_auth_main_screen.dart
lib/ui/widgets/no_connection_message.dart
pubspec.lock
pubspec.yaml

Chybova hlaska ohladom pripojenia bola vyriesena

Fix/aplikace zobrazuje chybovou hlasku o pripojeni k internetu#92

---

ios/Podfile.lock

fix: ios fix podfile

---

lib/constants.dart
lib/l10n/intl_cs.arb
lib/ui/widgets/consultancy/form/form_content.dart
lib/ui/widgets/consultancy/form/form_question_types_wrapper.dart

Processing the request for BE, to send label string instead of converted enum to string
Maped enum contra string labels

Fix/email dotaz na poradnu fix 2#486

---

lib/ui/screens/main/main_screen.dart

Bola opravena chyba s nacitanim prohlidek pri inicializacii MainScreen

fix: Added_examFetch_at_init

---

lib/router/notification_router.dart
lib/services/notification_service.dart

Po kliknuti na notifikaci sa appka zasekla na NotificationLoadingScreen

fix: notif stuck on loading screen
