lib/l10n/ext.dart
lib/l10n/intl_cs.arb
lib/ui/screens/onboarding/carousel/carousel_third.dart

I personally think that calling `AppLocalizations.of(context)!` (29 chars vs 12) every time is a bit unnecessarily long, the only downside with using extensions is that they must be manually imported..

Add extension method for Localizations

---

lib/ui/screens/onboarding/carousel/carousel.dart
lib/ui/widgets/onboarding/carousel/indicator.dart
lib/ui/widgets/onboarding/carousel/indicator_row.dart
lib/ui/widgets/onboarding/carousel/story_page.dart
lib/ui/widgets/onboarding/carousel/tap_area.dart

Otakar ještě dnes doplnil nějaké info k tomu carouselu:
- defaultně má trvat story 15s
- po doběhnutí animace se má samo skočit na další story (kromě poslední)

Onboarding carousel updates

---

lib/ui/screens/about_health/about_health.dart

po diskuzi na slacku s Evou Rippl, bude nový design webu O zdraví obsahovat embedované spotify podcasty. Požadované features jsou:
- inline přehrávání podcastu ve webview
- po tapnutí na "spotify" otevřít stránku podcastu na spotify. Buď spustí appku nebo fallbackne na spotify web
Tenhle PR whitelistuje hosta open.spotify.com a spouští mimo loono appku

feat: Loono podcast launcher

---

lib/ui/screens/main/pre_auth/continue_onboarding_form.dart
lib/ui/screens/main/pre_auth/onboarding_form_done.dart
lib/ui/screens/main/pre_auth/start_new_questionnaire.dart
lib/ui/screens/welcome.dart

upgradováním na Flutter 2.10.0 a upgradem auto_route knihovny se rozbily zase routy na přihlašovací obrazovku
([issue](https://github.com/Milad-Akarie/auto_route_library/issues/496): nedá se pushovat z dekalritvní na routu která má childy, tak je to takové ohackované alespoň že se pushne routa která nemá childy a pak s childama)

fix: onboarding routes

---

lib/l10n/intl_cs.arb
lib/ui/screens/prevention/examination_detail/new_time_screen.dart
lib/ui/widgets/custom_time_picker.dart
lib/ui/widgets/prevention/datepicker_sheet.dart
lib/ui/widgets/prevention/examination_edit_modal.dart

Opravuje stav, kdy u změny prohlídky uživatel nevybere čas. Padalo to na 00:00. 
Navíc teď předvyplňuje známý čas z minulé prohlídky.
Vyměněno jedno button bez loadingu a pár minor úprav.

fix: timepicker bugfixes

---

lib/models/firebase_user.dart
lib/ui/screens/main/pre_auth/onboarding_form_done.dart

@MartinMacek párkrát se mi stalo, že to API call failnul a stejně dalo na next screen. ~~Musíme pak nějak pořešit ten case pokud je server dole, na Firebase se mu stejěn účet založí. Pak se může v login screeně přihlásit, ale nikdy neuvidí svý data, protože se reálně neuložily na BE.~~ pokud request failne, smaže se účet z Firebase

fix: wait for user onboard

---

lib/repositories/examination_repository.dart
lib/services/api_service.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/screens/prevention/questionnaire/schedule_examination.dart
lib/ui/widgets/badges/badge_composer.dart
lib/ui/widgets/prevention/change_last_visit_sheet.dart
lib/ui/widgets/prevention/examination_cancel_sheet.dart
lib/ui/widgets/prevention/examination_confirm_sheet.dart
lib/ui/widgets/prevention/examination_edit_modal.dart
lib/ui/widgets/prevention/examinations_sheet_overlay.dart
lib/ui/widgets/settings/avatar.dart
lib/utils/registry.dart
pubspec.lock
pubspec.yaml

Aktualizovány všechny cally prevence na api podle dokumentu od Lukáše. Přepsal jsem aktuální stav do [(tohoto) sdíleného docu, který odpovídá tomuhle PR](https://docs.google.com/document/d/1M27Bhlucd_lyVo93eVWTcovqWsirKWlF0DPMPjhuqO0/edit?usp=sharing).
Přidán Dio interceptor na retry callů.
Fixnul problikávání hrdiny po načtení a zastropoval jsem badge levels na 5, aby se předešlo chybám.
note: code anchors slouží pro rychlejší navigaci mezi dokumetací a přesným místem v kódu.

feat: Prevention api calls update + retry interceptor

---

lib/helpers/examination_extensions.dart
lib/ui/widgets/prevention/examination_card.dart
lib/ui/widgets/prevention/examination_edit_modal.dart
lib/ui/widgets/prevention/examination_progress_content.dart

upravena počítání logika statusů
u těch statusů tam zůstala ještě logika z tý doby, kdy statusy nebyly, takže to vůbec nesedělo s tím co tam má být...
https://cesko-digital.atlassian.net/browse/LOON-525
https://cesko-digital.atlassian.net/browse/LOON-524

fix(prevention): main screen card statuses

---

ios/Podfile
ios/Runner/Info.plist

na ios se u permissions u kelandáře zobrazilo, že je vždy zakázané
https://cesko-digital.atlassian.net/browse/LOON-361

fix(permissions): ios calendar & notifications permissions

---

lib/main.dart
lib/utils/picture_precaching.dart
lib/utils/registry.dart

Scalable reseni, jak precachovat obrazky (nejen) na startupu appky. Vsechnu logiku a resources jsem extrahoval do zvlastniho souboru, kde jsou zatim jen 2 obrazky v listu, ale dobudoucna se muzou pridat dalsi listy s dalsimi obrazky a precachovat kdekoliv jinde ve flow appky.

LOON-367 precaching images

---

.github/workflows/tests.yml
android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
pubspec.lock

Zkouším přidat debugSymbolLevel který by měl nahrát debug symbols do google play a zbavit se tak jednoho warningu.
Musel jsem aktualizovat kotlin a gradle. První build trvá docela dlouho, než se všechno stáhne ale další už běží normálně.
Narazil jsem na nějaké čerstvé [issues](https://github.com/flutter/flutter/issues/99381) s nefunkčními flavors, tak uvidíme jestli na to narazíme taky. Musí to projít codemagicem aby došlo k podepsání bundlu.

feat(android): Add debugSymbolLevel

---

integration_test/test_helpers/dart_objects_gens.dart
lib/services/examinations_service.dart
lib/ui/screens/prevention/questionnaire/schedule_examination.dart
lib/ui/widgets/prevention/examination_edit_modal.dart
pubspec.lock
pubspec.yaml

- sjednocení s ostatními API cally, uuid se bude posílat rovnou nullable u prohlídek které nejsou v onboardingu
- fix 1 statusu

fix(api): prevention questionnaire fixes

---

lib/l10n/intl_cs.arb
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/widgets/prevention/datepicker_sheet.dart
lib/ui/widgets/prevention/examination_confirm_sheet.dart
lib/utils/image_utils.dart

https://cesko-digital.atlassian.net/browse/LOON-368
- Max velikost obrázků zastropována na 400px každé strany. (otevřen diskuzi o velikosti obrázku)
- Upraven context confirmation sheetu a následného AchievementScreenu, protože se passoval neexistujíci context stream builderu a nefungoval pop
- Přidána validace prohlídek povolující pouze datum v budoucnu. Vycházel jsem z [těchto acceptance criteria](https://cesko-digital.atlassian.net/browse/LOON-285)

feat(LOON-368): Image processing

---

lib/models/social_login_account.dart
lib/services/auth/auth_service.dart
lib/utils/crypto_utils.dart

- fixnuta jen registrace, testnuta že funguje by @PetrVachulka
- opětovné přihlášení se bude muset ještě pořešit (to nefungovalo AFAIK ani předtím).
> A ohledně zpětného loginu, v [dokumentaci](https://pub.dev/documentation/sign_in_with_apple_platform_interface/latest/authorization_credential/AuthorizationCredentialAppleID/email.html) jsem četl že email jde získat jen 1x a pak ho už nevíme. A abychom zjistili, jestli existuje účet, tak na to používáme metodu [fetchSignInMethodsForEmail](https://pub.dev/documentation/firebase_auth/latest/firebase_auth/FirebaseAuth/fetchSignInMethodsForEmail.html) z Firebase.. jenže když ten email nevíme tak nezjsitíme jestli účet s tím mailem existuje.. říkal jsem to kdysi s [@Jana Hejnova](https://cesko-digital.slack.com/team/U017YUFFX2S), ale už nevím …

fix(auth): sign up with apple

---

lib/ui/screens/main/pre_auth/login.dart
lib/ui/screens/main/pre_auth/onboarding_form_done.dart

Self explanatory. Prihlasit se pres Apple na androidu nam atm nefunguje, takze je dobry napad tuto moznost uplne schovat. Dobudoucna se nejak tento login da resit i na androidu, ale to bude chtit vetsi poinvestigovani, je to dost corner case a neni to potreba v MVP.

Show apple social buttons only on ios

---

lib/models/examination_questionnaire.dart

Pokud se zadá v onboardingu "Nevím", vyskočí pak v registraci error. Způsobila předtím změna že se posílal DateTime v UTC

fix(onboarding): date time interval api error

---

README.md
lib/services/firebase_storage_service.dart
lib/utils/app_clear.dart
lib/utils/registry.dart

- enabled Crashlytics in non-debug mode (test crash se projevil se v konzoli)
- disabled Analytics in debug mode
- delete user files from FB Storage on delete account
a ještě setupnuto FB Storage, ale v kodu asi zadne změny nejsou třeba
mensi update starych instrukci v Readme

feat(firebase): more setups, delete user files on delete account

---

lib/services/notification_service.dart

Přidán notification open handler který pushne danou examination po tapnutí na notifku na základě jejího typu. 
Z notifikací čte additional data s klíčem `examinationType` a jako value rozeznává **examinationType** nebo **selfExamination.type**.
Povolené values jsou tedy: `COLONOSCOPY`,`DENTIST`,`DERMATOLOGIST`,`GENERAL_PRACTITIONER`,`GYNECOLOGIST`,`MAMMOGRAM`,`OPHTHALMOLOGIST`,`TOKS`,`ULTRASOUND_BREAST`,`UROLOGIST`,`VENEREAL_DISEASES` 
nebo 
`BREAST`,`TESTICULAR`

feat(notification): Navigate to examinations

---

lib/ui/screens/settings/settings_bottom_sheet.dart
lib/ui/widgets/close_button.dart
lib/ui/widgets/feedback/feedback_form_content_sheet.dart
lib/ui/widgets/feedback/rating_bottom_sheet.dart
lib/ui/widgets/find_doctor/doctor_detail_sheet.dart
lib/ui/widgets/find_doctor/specialization_chips_list.dart
lib/ui/widgets/find_doctor/specializations_list_sheet.dart
lib/ui/widgets/settings/app_bar.dart

- fix: na pre-auth nešly popovat routy z bottom sheetu (ani u specializací)
- adjustments na malých devices u feedback form - na malých se volá action Done z klávesnice, aby se skryla klavesnice a mohlo to odeslat. Měl jsem report, že ne úplně všem je jasné jak skrýt klávesnici - čekám ještě na nějake confirms jak to handlovat
- přidán splash efekt k některým buttonum který ho neměly

fix(ui): feedback form adjustments

---

lib/services/map_state_sevice.dart
lib/ui/widgets/find_doctor/map_preview.dart

Dávám jako první výstřel k diskuzi. Skrývám doktory za bottom map overlayem ale někdy se ty clustery stejně chovají zvláštně z nějakého jiného důvodu. 
S tímhle řešením by šlo snadno skrývat i doktory za inputem.
Velká nevýhoda tohoto řešení je, že jsem musel vypnout rotaci na mapě. Dopočítávání boundaries na mapě ve spojení s rotací je vyšší dívčí :D WDYT @mzdm je vypnutí rotace velký problém?

fix(LOON-647): Hide doctors behind bottom sheet

---

lib/helpers/date_helpers.dart
lib/services/api_service.dart
lib/ui/screens/onboarding/fallback_account/email.dart

tedkom se teda posílá se pravý (neshiftnutý na local) UTC date
[BE test](https://github.com/cesko-digital/loono/runs/6377510558?check_suite_focus=true) prošel

fix(api): send not shifted UTC date

---

lib/ui/widgets/async_button.dart

neprochazi kvuli tomu test viz Firebase Test Lab logy
```dart
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following assertion was thrown running a test:
setState() called after dispose():
_AsyncLoonoLightApiButtonState#42770(lifecycle state: defunct,
not mounted)
This error happens if you call setState() on a State object for a
widget that no longer appears in the widget tree (e.g., whose
parent widget no longer includes the widget in its build). This
error can occur when code calls setState() from a timer or an
animation callback.
The preferred solution is to cancel the timer or stop listening
to the animation in the dispose() callback. Another solution is
to check the "mounted" property of this object before calling
setState() to ensure the …
```

fix: memory leaks

---

lib/ui/screens/about_health/about_health.dart
pubspec.lock
pubspec.yaml

https://cesko-digital.atlassian.net/browse/LOON-677
Zatím aspoň progress indicator, aby šlo vidět, že se něco děje. Zatím moc nevím jak zkrátit load time.
Update webview balíčku, který by měl řešit 2 [android crashes](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1159) z analytics

feat(LOON-667): Webview loading indicator, package update

---

lib/repositories/healthcare_repository.dart
lib/ui/screens/find_doctor/find_doctor.dart
lib/utils/memoized_stream.dart

jen menši přepoužitelná utilita, která využívá `MemoizedStream` a `MemoizedStreamBuilder`, pro managování stavů v appce (alternativa provideru), kde není přístup ke kontextu, například z `repositories`. Vyextrahoval jsem ten z healthcare_repository.dart a použil to rovnou na tom

feat: reusable memory storage utility

---

android/app/src/main/AndroidManifest.xml

Crash se se dá snadno reprodukovat při zapnutém v dev settings 'Neponechat žádné aktivity', když se minimalizuje appka. Po znovu otevření crashnula, takhle by se měla alespoň spustit odznovu.
Fix z:
https://pub.dev/packages/flutter_native_splash#i-got-the-error-a-splash-screen-was-provided-to-flutter-but-this-is-deprecated Nezmiňuje se tam že to vyloženě fixuje tento issue, ale po odstranění se už mi to nestalo.. předtím se to stávalo furt. Pokud to není úplný fix, snad by to mělo aspoň zredukovat počet :D
Btw dle https://github.com/flutter/flutter/issues/94329 by to mělo být fixed už ve frameworku, možná nějaký konflikt mezi tou knihovnou a oficiálním splashem 🤷‍♂️

fix: crash when re-launching app from background

---

lib/services/auth/failures.dart

Jana testovala sign in with Apple mezi více devices a funguje to (my sice apple email cachujem jen lokálně, ale naštěstí [Keychain syncuje sám Apple mezi devices](https://support.apple.com/en-us/HT204085)), takže o starost míň :D
Jen teda může být edge case že na 1 devicu nám email řekne ale na druhým anonymizuje (xyz@privaterelay.appleid.com). Proto tam vracím tu hlášku o neexistujícím xyz emailu i když je ten email random, aby jim to případně došlo if it makes sense

feat(auth): add back anonymized apple email to error message

---

integration_test/test_helpers/widget_tester_extensions.dart
integration_test/test_sets/app/test_cases/be_flow.dart
integration_test/test_sets/app/test_cases/loon_580_force_update.dart
integration_test/test_sets/onboarding/test_cases/other/loon_671_login_server_down_block_user.dart
integration_test/test_sets/onboarding/test_cases/questionnaire/loon_558_onboarding_age_validation.dart

po poslední změně [BE testy failujou](https://github.com/Loono-cz/loono/actions/workflows/backend-tests.yml), protože se snažilo popnout screenu těsně po zobrazení toast message, teď se nejprve čeká až se zobrazí a zase zmizne a pak teprve popuje

fix(tests): add new helper method for handling toast messages

---

lib/helpers/examination_types.dart
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/widgets/prevention/examination_confirm_sheet.dart

po potvrzení že byl/a na prohlídce se u některých doktorů v Award sceeně ukázalo, že získal 0 bodů
~~(je to hardcodované, ale z API typ `ExaminationRecord` nám počet bodů neposílá)~~ // tak jde to z API, ale nechal jsem to v tom switchi, který se použivá v onboardingu kde není přístup k API :D

fix(ui): showing zero points award from undergone examination

---

lib/helpers/flushbar_message.dart
lib/l10n/intl_cs.arb
lib/ui/screens/prevention/examination_detail/examination_detail.dart
lib/ui/widgets/prevention/self_examination/self_examination_card.dart

Odstraněn reverse historie samovyšetření v kartě. 
Zároveň jsem s Radkem testoval 2. samovyšetření a zdá se to být fixrd na BE.
Postup testování:
1. vytvořil jsem první samovyšetření - plannedDate se změnilo na 2022-07-17
2. Radek změnil plannedDate na dnešek
3. appka umožnila udělat 2. samovyšetření a přidělila druhou fajfku v kartě i v detailu

fix(UI): Reverse self exam badges

---

lib/ui/screens/prevention/examination_detail/examination_detail.dart

Fixes https://cesko-digital.slack.com/archives/C01P6CK0DDY/p1656936976071359
Pokud se přidala prohlídka do kalendáře, pak nešlo vidět to tlačítko na potvrzení. 
Yep ty podmínky tam v `examination_detail.dart`, by potřeboval asi refaktor :D

fix(ui): missing check-up confirmation button

---

integration_test/mocks/firebase_auth_mock.dart
integration_test/mocks/google_sign_in_mock.dart
lib/services/map_state_sevice.dart
lib/ui/screens/prevention/examination_detail/faq_section.dart
lib/ui/widgets/find_doctor/map_preview.dart
lib/utils/registry.dart
pubspec.lock
pubspec.yaml

#347 nějak upgradnulo `google_sign_in` package na vyšší verzi, který nepoužívá už` Platform Channely` ale `Pigeon`, takže mocky přestaly fungovat - zobrazoval se ten přihlašovací dialog. Workaround - revertnul jsem verze tak jak byly předtím. Až se bude chtít upgradovat `firebase_auth` a `google_sign_in` tak se budou muset ty mocky přepsat
btw myslím že 2 testy failujou ale blíže jsem nekoukal

fix(tests): revert to old mock interface API

---

lib/ui/widgets/consultancy/form_card.dart

wrap textu form karticky jako osetreni proti pretekani na malem displeji (iPhone SE 1. gen)

fix: form card overflow in small screens
